### ISSUE TITLE
Grayscale images result in palette with colors

### ISSUE THREAD

**Issue by rayshan** [akfish/node-vibrant#16]
Hi, all grayscale images, for example:
https://www.facebook.com/photo.php?fbid=10107296866472911&l=bb741fb5ef

Generates these swatches in v2.0.0 with default options:

```js
{ Vibrant:
   Swatch {
     rgb: [ 144, 72, 192 ],
     population: 0,
     hsl: [ 0.7666666666666666, 0.4878048780487805, 0.5176470588235293 ] },
  Muted:
   Swatch {
     rgb: [ 140, 140, 140 ],
     population: 548,
     hsl: [ 0, 0, 0.5490196078431373 ] },
  DarkVibrant:
   Swatch {
     rgb: [ 48, 116, 116 ],
     population: 0,
     hsl: [ 0.5, 0.41463414634146345, 0.32156862745098036 ] },
  DarkMuted:
   Swatch {
     rgb: [ 100, 100, 100 ],
     population: 1561,
     hsl: [ 0, 0, 0.39215686274509803 ] },
  LightVibrant:
   Swatch {
     rgb: [ 200, 80, 204 ],
     population: 0,
     hsl: [ 0.8279569892473119, 0.5486725663716815, 0.5568627450980392 ] },
  LightMuted:
   Swatch {
     rgb: [ 156, 156, 156 ],
     population: 514,
     hsl: [ 0, 0, 0.611764705882353 ] } 
}
```

All the `*Vibrant` swatches are not grayscale. I think the user would expect all swatches to be grayscale. I reported this issue previously for vibrant.js: https://github.com/jariz/vibrant.js/issues/18. I was hoping updated algorithm will help with this but it doesn't. Is this something node-vibrant can help with, or should we do grayscale detection separately?

**Comment by akfish** [comment]
You can do it with `Filter` now. Something like:

```coffee
Vibrant.from('path/to/grayscale.jpg')
  .addFilter((r, g, b, a) -> r == g and r == b and g == b) # Grayscale color only
  .getPalette (err, palette) ->
    # Do something
```

I wouldn't expect great result, since there's nothing vibrant about a grayscale image. 

FYI, the Android M's Palette algorithm is almost identical with the original one. Though its optimization approach does not work well in browser/node environment. So 2.0.0's algorithm basically remains the same as before, except for the optimization, some fixes and tweaks.

**Comment by rayshan** [comment]
Filter works for this if we know whether the image is grayscale to begin with. I would prefer not to spend the extra resources to analyze the image separately if possible, such as using https://github.com/Pomax/RGBAnalyse.

I noticed after trying a few grayscale images, all the `*Muted` swatches have rgb values equal to each other, so I'll probably check them after palette is generated, and use `*Muted` swatches only for grayscale images.

We do have to check all the `*Muted` swatches though. Sometimes a less colorful image such as this one:

![our-omnipotent-overlord 1x](https://cloud.githubusercontent.com/assets/3760840/10856180/318a374e-7f03-11e5-8cf0-3891711016ce.jpeg)

May generate a `*Muted` swatch that's grayscale:

```js
{ Vibrant:
   Swatch {
     rgb: [ 192, 160, 80 ],
     population: 0,
     hsl: [ 0.11904761904761905, 0.47058823529411764, 0.26 ] },
  Muted:
   Swatch {
     rgb: [ 156, 156, 156 ],
     population: 1152,
     hsl: [ 0, 0, 0.611764705882353 ] },
  DarkVibrant:
   Swatch {
     rgb: [ 97.50000000000001, 79.67142857142858, 35.099999999999994 ],
     population: 0 },
  DarkMuted:
   Swatch {
     rgb: [ 79, 98, 125 ],
     population: 4122,
     hsl: [ 0.5978260869565217, 0.22549019607843132, 0.4 ] },
  LightVibrant: null,
  LightMuted:
   Swatch {
     rgb: [ 163, 164, 164 ],
     population: 1277,
     hsl: [ 0.5, 0.005464480874317074, 0.6411764705882352 ] } }
```

Thanks for the note on the algorithm. Please close this issue if you think it's outside the scope of this library.

**Comment by akfish** [comment]
I wouldn't be surprise that palettes of gray scale images will end up looking somewhat the same, since there are only (at most) 256 colors to begin with. 
Come to think about it, graysacle images should be rare cases in the normal use cases for this library. Even though we can surely add some built-in mechanism to detect one and do stuff accordingly, it wouldn't be cost-effective to do so.

For your second question, muted colors, by definition, are primary or secondary colors mixed with grey to "tone" them down. They are expected to be dull, pale or less intense. An image with lesser color count may get a muted swatch that is grayscale (downsampling may make it worse). The dark muted and light muted swatches (last two in the following image), if they are available, may have more color component. 
![image](https://cloud.githubusercontent.com/assets/922715/10860575/27a266f0-7fa5-11e5-86ec-b666cfb25c5e.png)

If performance is not too much of an issue, I would suggest using the highest quality possible (the above palette is generate with quality = 1). It would look better when images have lesser color. 

I will revisit the second question when I have time to play with the generator algorithm. Close for now.

- [ ] Idea: generate DarkVibrant, LightVibrant, DarkMuted, LightMuted from Vibrant and Muted if they are not available.

**Comment by rayshan** [comment]
> graysacle images should be rare cases in the normal use cases for this library. 

I agree if you have grayscale images you wouldn't want to use this library. I would think most users are just programmatically processing unknown image input. My use case is a bunch of photographs. iTunes' use case is a bunch of album covers. All of these may include grayscale images.

Thanks for the explanation. It's interesting to learn about how things work. I'll use your suggestion of higher quality.
