### ISSUE TITLE
Restrict output to a predefined array of colours

### ISSUE THREAD

**Issue by tyssen** [akfish/node-vibrant#18]
I'd like to use Vibrant to help populate a database of products with colour information to be used in a colour search feature. I'd like to restrict the number of colours that people can search on so it doesn't get overwhelming. 

So, for example, if an image has 8 hues of blue in it, Vibrant would only output a single object with the hex value equal to one I've previously selected as the default value for blue.

Is it possible to do that with Vibrant?

**Comment by akfish** [comment]
Off the top of my mind, there're a few possible approaches to do it such as custom filter or generator. But the easiest way is to approximate generated colors to ones in your color list.
Basically you just need to find the color with minimum [color delta](https://github.com/akfish/node-vibrant#deltae94lab1-lab2) against generated one as its approximation.

**Comment by tyssen** [comment]
Could I trouble you to give me an example of how that might work incorporated into the example included?

    Vibrant.from(src).getPalette(function(err, swatches) {
      if (err) throw err;
      console.log(swatches);
      for (var key in swatches) {
        var swatch = swatches[key];
        if (swatch) {
          var hex = swatch.getHex();
          console.log(key + ": " + hex);
          addColorBlock(hex);
        }
      }
    });

**Comment by akfish** [comment]
Sure, something like:

```js
var colors = []; // your color list in hex values

function approximate(color, list) {
  var minDelta = 100, 
    appr = color;
  for (var i = 0; i < list.length; i++) {
    var delta = Vibrant.Util.hexDiff(color, list[i]);
    if (delta < minDelta) {
      minDelta = delta;
      appr = list[i];
    }
  }
  return appr;
}

Vibrant.from(src).getPalette(function(err, swatches) {
  if (err) throw err;
  console.log(swatches);
  for (var key in swatches) {
    var swatch = swatches[key];
    if (swatch) {
      var hex = swatch.getHex();
      console.log(key + ": " + hex);
      var approx = approximate(hex, colors);
      addColorBlock(approx);
    }
  }
});
```

**Comment by tyssen** [comment]
Excellent, thanks. :)

**Comment by akfish** [comment]
No problem

**Comment by tyssen** [comment]
Is there a way to relax or loosen the `hexDiff` function to adjust the results?
For the most part I'm getting fairly close to what I want but there's a few examples where some obvious colours are missing, e.g.:

![3](https://cloud.githubusercontent.com/assets/370290/12084905/20c9af3a-b305-11e5-938d-90b16b22c8f1.png)
this one has some blue in it

![1](https://cloud.githubusercontent.com/assets/370290/12084906/20cd6d14-b305-11e5-9d3f-cec41b2f7a68.png)
this one has some red and pink

![2](https://cloud.githubusercontent.com/assets/370290/12084907/20d24cf8-b305-11e5-810e-f63970bd4531.png)
and this one has acqua

The colours I've mentioned are all included in my list.
I've tried adjusting the `minDelta` value but it outputs hex values that don't match my list if I go lower than 100.

**Comment by akfish** [comment]
The `approximate` function provided above is intended to find a color with minimum delta in your list. A color delta value is in the range of 0~100. Hence `minDelta = 100` is the initialization value (as it's the maximum delta value) and it's not tweak-able. The value ranges and their meanings are documented [here](https://github.com/akfish/node-vibrant#getcolordiffstatusd). See also:
* [color difference](https://en.wikipedia.org/wiki/Color_difference)
* [Learn Delta E](http://zschuessler.github.io/DeltaE/learn/)

Color difference equation is just an empirical approach to quantize human eyes' color perception. It's not perfect but wouldn't be far off. Though I wouldn't expect it to work for every images given the subjective nature of human perception (some examples are given in the last reference article above). 

The color list matters too. It should contains reasonable amount of colors that are reasonably spreaded across color space.

My suggestions are:
* Try set `quality=1`. Those dominating greyish color in last picture might be downsampling artifact.
* Generate all possible hex color values and approximate them against your color list. Output the approximated value and the original value side-by-side along with the color delta value. Visually confirm how well the approximations are and tweak the list accordingly.

If none of that improves your situation, probably you should try search some other libraries specialized for your application. Since color delta is only used for unit testing in this project and color approximation is not exactly in its scope.
