### ISSUE TITLE
more than one color from image?

### ISSUE THREAD

**Issue by chovy** [akfish/node-vibrant#20]
Is it possible to get more than one color from an image?

I'm looking at a tool like this: http://www.pictaculous.com/ which will pick the 4 dominant (?) colors from an image. Is this possible with node-vibrant?

**Comment by akfish** [comment]
It is achievable with a custom [`Generator`][1]. The quantization stage will generate colors up to the amount specified by `opts.colorCount` and they are feed to `Generator` for the final selection. 

The default generator would be a good start. For example, you could modify [this method][2]. Instead of selecting a single color maximum comparison value, you can sort colors by comparison values and select top ones.

[1]: https://github.com/akfish/node-vibrant#vibrantgenerator
[2]: https://github.com/akfish/node-vibrant/blob/master/src/generator/default.coffee#L98

**Comment by chovy** [comment]
Is there anyway to get a list of the 64 colors it found?

**Comment by akfish** [comment]
All colors are passed to `Generator.generate` method directly as shown [here][1].

[1]: https://github.com/akfish/node-vibrant/blob/master/src/vibrant.coffee#L59

**Comment by chovy** [comment]
I meant is there a public function off the `v` object I can call to return all the colors it found.

**Comment by akfish** [comment]
Nope.
